# Introduction {#intro}

## Directions to start a book (after downloading packages described)

1. Open R Studio
2. File - New Project - New Directory - New Book Project 
3. Save where you think it should be.
4. To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>.
5. If you have errors when trying to compile the book, go to the debug website provided in your warnings.


## Structure of book
* There will be multiple Rmd (R Markdown) files - one for each chapter.
* File naming: 
  + index.Rmd
  + 01-yourchapter1title.Rmd
  + 02-yourchapter2title.Rmd  
* Each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

## Other tips
* In your _output.yml file: delete 
"bookdown::pdf_book:
  includes:
    in_header: preamble.tex
  latex_engine: xelatex
  citation_package: natbib
  keep_tex: yes" and replace the 
"bookdown::epub: default" with
"bookdown::html_document2: default"

* In your index.Rmd file, add "always_allow_html: yes" to the options at the top
