# Interactive tools

## Plotly {.tabset}

Install plotly.

### Code
```{r plotly, warning = FALSE, message = FALSE}
library(plotly)
data("iris")

summary(iris)
```

### Plot
Different ways to code: 
```{r plotlyPlot, warning = FALSE, message = FALSE}
plot_ly(iris, x = ~Sepal.Width, y = ~Sepal.Length, type = "scatter", 
        hoverinfo = "text",
        text = ~paste('</br> Species: ', Species,
                      '</br> Petal Length: ', Petal.Length,
                      '</br> Petal Width: ', Petal.Width))

iris %>%
  plot_ly(x = ~Sepal.Length, y = ~Petal.Length) %>%
  add_lines()

p <- ggplot(iris, aes(x = Sepal.Width, y = Sepal.Length)) + facet_wrap(~Species) +  geom_point()
ggplotly(p)
```

## Leaflet
Install leaflet.

```{r leaflet, warning = FALSE, message = FALSE}
library(leaflet)
library(viridis)
library(lubridate)
Stations <- read.csv("StationsMetadata.csv")
summary(Stations)

Station2 <- Stations %>%
  mutate(Year1 = year(as.Date(StartDateDataset, format = "%m/%d/%Y")),
         Year2 = year(as.Date(EndDateDataset, format = "%m/%d/%Y")),
         Range = Year2-Year1)

```

Make map - Color by factor

```{r leafletMap, warning = FALSE, message = FALSE}
# Palette from viridis
  staPal <- colorFactor("viridis", domain = Stations$Agency)
  
Stations %>% # name of data
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    color = ~staPal(Agency),
    stroke = FALSE,
    fillOpacity = 0.9,
    lng = ~Longitude,
    lat = ~Latitude,
    labelOptions = labelOptions(noHide = F),
    popup = ~paste(Station, ":", StationName, "<br/>",
                   "Agency:", Agency)) %>%
    addLegend(pal = staPal,
            values = ~Agency,
            position = "bottomright")

```

Make map - size and color by numeric

```{r}
staPal2 <- colorNumeric("viridis", domain = Station2$Range)

Station2 %>%
  leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    color = ~staPal2(Range),
    radius = ~Range,
    stroke = FALSE,
    fillOpacity = 0.5,
    lng = ~Longitude,
    lat = ~Latitude,
    labelOptions = labelOptions(noHide = F),
    popup = ~paste(Station, ":", StationName, "<br/>",
                   "Agency:", Agency)) %>%
    addLegend(pal = staPal2,
            values = ~Range,
            position = "bottomright")
```

